spring:
  application:
    name: adidas-product-creation-client
  data:
    neo4j:
      username: neo4j
      password: neo4j
      uri: bolt://neo4j:7687
#     uri: bolt://localhost:7687
        
server:
      port: 0      
      

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://discovery-eureka:8761/eureka,http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    

    

