version: '2.2'

services:
    discovery-eureka: 
      container_name: adidas-product-creation-service-registry
      build:
            context: .
            dockerfile: adidas-product-creation-service-registry/Dockerfile
      image: adidas-product-creation-service-registry:latest
      expose:
        - 8761
      ports:
        - 8761:8761
      networks:
        - emp-network
       
    product-creation-client:
      container_name: adidas-product-creation-client
      build:
        context: .
        dockerfile: adidas-product-creation-client/Dockerfile
      image: adidas-product-creation-client:latest
      entrypoint: /opt/bin/client-entrypoint.sh
      expose:
        - 8084
      ports:
        - 8084:8084
      networks:
        - emp-network
      links:
        - discovery-eureka:adidas-product-creation-service-registry
      depends_on:
       - discovery-eureka

    product-creation-rest:
      container_name: adidas-product-creation-rest
      build:
        context: .
        dockerfile: adidas-product-creation-rest/Dockerfile
      image: adidas-product-creation-rest:latest
      entrypoint: /opt/bin/rest-entrypoint.sh
      expose:
        - 8080
      ports:
        - 8080:8080
      networks:
        - emp-network
      links:
      - discovery-eureka:adidas-product-creation-service-registry
      depends_on:
       - discovery-eureka
       
    neo4j:
        container_name: neo4j-db
        build:
            context: .
        image: marcellodesales/neo4j-with-cypher-seed:latest
        environment:
      # - NEO4J_AUTH=neo4j/test # Just click on the login button without password
            - NEO4J_AUTH=none # Just click on the login button without password
      # - NEO4J_USERNAME=neo4j
      # - NEO4J_PASSWORD=test
        ports:
            - 7474:7474  # Go to http://localhost:7474/browser/ after bootstrapping
            - 7687:7687
        networks:
            - emp-network
        volumes:
            - ./neo4j-runtime/data:/data"
            - ./neo4j-runtime/logs:/logs"
            - ./neo4j-runtime/import:/var/lib/neo4j/import"
            - ./neo4j-runtime/plugins:/plugins"
            - ./cypher_query.cql:/cyphers/interviews.cql
       

networks:
    emp-network:
        driver: bridge